### PR TITLE
Add support for gene symbols specified in columns other than the var.index

### LINKED ISSUE #72: celltypist fails with value error
### Description of the bug

I ran `scdownstream` on the h5ad output of `nf-core/scrnaseq` using cellranger. `scdownstream` fails on celltypist giving this error:

`ValueError: 🛑 No features overlap with the model. Please provide gene symbols`

To track down what is going one, I loaded the input h5ad manually using scanpy. I could see that the AnnData object has gene ids in var_names. But celltypist needs gene symbols. 

I believe we need to make celltypist aware of where to look for gene symbols. How? We could specify a var column as a parameter in the samplesheet to select the column for gene symbols. Or we could implement an option to automatically convert gene ids. Or the celltypist process could get an additional parameter to select a column where to look for gene symbols? Not sure. I can try to provide a MWE, let me know if this is needed.

### Command used and terminal output

_No response_

### Relevant files

_No response_

### System information

_No response_

### PR DESCRIPTION
**Pull request by nictru**
This PR adds documentation and a basic implementation of this feature. Some questions need to be cleared before merging:
1. Does the `gene_symbol` column survive AnnData concatenation?
2. What happens if there are duplicates in the `gene_symbol` column but not in the `var_names`?

### CODE REVIEW

**Comment by nictru** [comment]
@fbnrst, is this approximately what you imagined? I didn't test it yet, but if you want you can give it a go and let me know if something needs to be changed

**Comment by fbnrst** [comment]
This is how I imagined it, and I am running a test right now. But your points are very valid and it is not clear to me how duplicate `var_names` should be handled. I checked celltypist a little, and their approach seems to be that you can convert the models using a mapping file that maps from IDs to symbols, see e.g. https://github.com/Teichlab/celltypist/issues/87
They also provide some mappings from Ensembl to gene symbols: https://github.com/Teichlab/celltypist/tree/main/celltypist/data/samples

There, they also provide files for other species and of course this is another relevant point, celltypist was developed having human in mind. 

So: What about using the mapping file instead of providing gene symbols column?
Also, after realising the species issue, it might be good to be able to skip cell typing as well, sometimes, without a good reference, this might not make sense.

**Comment by nictru** [comment]
Celltypist is already optional, it will only be executed if a celltypist model is provided as a parameter

**Comment by fbnrst** [comment]
My test run failed because the `gene_symbol` column was not available. I checked the `combine/merge/merged_outer.h5ad` in the outputs, which I believe is read by celltypist. I think the concatenation needs to be changed like this by adding a merge argument: 

```python
adata_outer = ad.concat(adatas, join="outer", index_unique="-", merge="unique")
```
https://github.com/fbnrst/scdownstream/blame/1d9f724e39a12211b5d36950e06656dc46e913ec/modules/local/adata/merge/templates/merge.py#L32

I am currently running a test on this again.

But I realised another thing:
When doing an outer merge 0s are filled in the count matrix (see the warning under notes here: https://anndata.readthedocs.io/en/latest/generated/anndata.concat.html). I think this is not generally correct, because missing data for that gene does not mean it was not expressed. 
I wonder whether it would be better to run celltypist on the inner join, or alternativly, to run celltypist on the individual samples before merging.

**Comment by fbnrst** [comment]
I created #74 to fix some little things, with those, I managed to run the pipeline using gene symbols for cell typist

**Comment by nictru** [comment]
> When doing an outer merge 0s are filled in the count matrix (see the warning under notes here: https://anndata.readthedocs.io/en/latest/generated/anndata.concat.html). I think this is not generally correct, because missing data for that gene does not mean it was not expressed.

True. The outer join is generally done so that people don't wonder why their favorite genes are not present in the output object. Filling with `NaN` would hugely increase dataset size, as it would need to be explicitly stored in sparse matrices.

Running celltypist per dataset before merging would a good solution I think

**Pull request merged**
